import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header, UpperNavbar, Footer } from "@/components";
import { Theme } from "@radix-ui/themes";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <UpperNavbar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
